export default [
  {
    headlineIncludes: [
      'Classroom Course',
      'Updated Training Course',
      'New AWS Training Course',
      'Course on Coursera',
      'New instructor-led course',
      'first technical course',
      'AWS Educate',
      'digital curriculum',
      'digital training curriculum',
    ],
    headlineMatches: [
      /Digital Courses?/i,
      /Digital training Courses?/i,
      /New self-paced courses?/i,
      /^New Course on/i,
      /AWS Classroom Training Courses?/i,
      /New AWS .+course for/i,
      /AWS.*Courses.*edX/i,
      /AWS.*Courses.*Udemy/i,
      /AWS.*Courses.*Coursera/i,
      /Exam Readiness Courses?/i,
      /new training courses?/i,
      /Accreditation Courses? Available/i,
      /New courses? available/i,
      /updates to.+AWS Courses/i,
      /Specializations? on Coursera/i,
      /on-demand training courses?/i,
      /^New courses?/i,
      /\d new courses?/i,
      /\d .+ updated courses?/i,
      /introducing.+courses?/i,
      /APN Partner Courses?/i,
      /edX.*new.*course/i,
      /coursera.*new.*course/i,
      /udemy.*new.*course/i,
      /announces new courses?/i,
      /course.+on.+coursera/i,
      /updated.+aws.+courses?/i,
      /series.+edX/i,
    ],
  },
];
