export default [
  {
    headlineIncludes: [
      'AWS Partner Network',
      'APN Partners',
      'APN Partner',
      'APN Navigate Foundations Path',
      'APN Consulting Partners',
      'partner integrations',
      'partner training',
      'AWS Training Partner',
      'AWS Partners',
      'Partner Services',
      'AWS and partners',
    ],
    headlineMatches: [
      /^APN/i,
      /^New APN/i,
      /APN.+track/i,
      /APN.+AWS Partners/i,
      /Introducing.+(AWS|Amazon).+Partner/i,
      /AWS Solutions?.+for Partners/i,
      /(Amazon|AWS).+Partners with/i,
      /AWS.+Partner Program/i,
      /new.+aws.+partners/i,
      /(Amazon|AWS).+adds.+partners?/i,
      /(Amazon|AWS).+integrations?.+partners/i,
      /(Amazon|AWS).+delivery.+partners/i,
      /(Amazon|AWS).+new.+partner/i,
      /(Amazon|AWS).+launches.+partner/i,
      /announcing.+aws.+partners/i,
      /(Amazon|AWS).+partner.+solution/i,
    ],
  },
];
