export default [
  {
    headlineIncludes: [
      'Supports Tagging',
      'tagging support',
      'tag your ',
      'Resource Tagging',
      'Resource Tags',
      'tagging capabilities',
      'Announcing Tagging',
      'you can tag',
      'supports tags',
      'support for tagging',
      'Copy Tags',
    ],
    headlineMatches: [
      /tag.on.create/i,
      /Cost Allocation Tag.*/i,
      /tagging.+creation/i,
      /allows.+tagging/i,
      /tagging.+available/i,
      /tag updat.+/i,
      /now use.+tags/i,
      /Resource Groups Tagging API.+support/i,
      /Resource Groups Tagging API.+launch/i,
      /tag.+in.+console/i,
      /supports.+tagging/i,
    ],
  },
];
